In [ ]:
#1

import numpy as np

arr = np.arange(1, 11)

print("Array:", arr)

sum_elements = np.sum(arr)
print("Sum:", sum_elements)

mean_elements = np.mean(arr)
print("Mean:", mean_elements)

std_dev = np.std(arr)
print("Standard Deviation:", std_dev)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Sum: 55
Mean: 5.5
Standard Deviation: 2.8722813232690143


In [ ]:
#2

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print("Array:", arr)

second_element = arr[1]
fourth_element = arr[3]
print("Second Element:", second_element)
print("Fourth Element:", fourth_element)

third_onwards = arr[2:]
print("Elements from Third Onwards:", third_onwards)

reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)


Array: [10 20 30 40 50 60]
Second Element: 20
Fourth Element: 40
Elements from Third Onwards: [30 40 50 60]
Reversed Array: [60 50 40 30 20 10]


In [ ]:
#3

import numpy as np

arr_1d = np.arange(1, 13)

print("Original Array:", arr_1d)

arr_2d = arr_1d.reshape(3, 4)
print("Reshaped Array:\n", arr_2d)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#4

import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print("Array A:", A)
print("Array B:", B)

addition = A + B
print("Addition:", addition)

subtraction = A - B
print("Subtraction:", subtraction)

multiplication = A * B
print("Element-wise Multiplication:", multiplication)

division = A / B
print("Element-wise Division:", division)



Array A: [1 2 3]
Array B: [4 5 6]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]
